@startuml
class Alerta {
    - fechaReporteDelIncidente: LocalDateTime
    - heladera: Heladera
    - tipoAlerta: TipoAlerta
}

enum TipoAlerta {
    TEMPERATURA
    FRAUDE
    DESCONEXION
}

Alerta -> TipoAlerta
@enduml